###############################################################################
#  Image: mucoll-ilc-base
###############################################################################

ARG VERSION=devel
ARG REPOSITORY=infnpd
FROM ${REPOSITORY}/mucoll-environment:${VERSION}-centos8stream

RUN cd /opt && git clone https://github.com/kkrizka/MuonCutil.git && \
    git clone https://github.com/MuonColliderSoft/iLCInstall.git && \
    cd /opt/MuonCutil && git checkout v02-08-MC && \
    cd /opt/iLCInstall && git checkout v02-03-01-MC && \
    mkdir releases/development && \
    cp /opt/MuonCutil/releases/development/* releases/development && \
    ./ilcsoft-install releases/development/release-base.cfg --install-prefix=/opt/ilcsoft -v -i


